#pragma once

#include "VectorBracket.h"
#include "VectorCopyFrom.h"
#include "VectorDeduplicate.h"
#include "VectorEqual.h"
#include "VectorExpand.h"
#include "VectorFind.h"
#include "VectorInsert.h"
#include "VectorRemove.h"
#include "VectorSearch.h"
#include "VectorShrink.h"
#include "VectorSort.h"
#include "VectorTraverse.h"
#include "VectorUniquify.h"
//Sort Methods
#include "sort/Bubble.h"
#include "sort/Merge.h"
#include "sort/Selection.h"